### ISSUE TITLE
PHP Parse error / unexpected end of file

### ISSUE THREAD

**Issue by lostfocus** [wp-cli/eval-command#20]
I just tried to use wp-cli to eval a pretty simple script and I keep running into the same error:

```
PHP Parse error:  syntax error, unexpected end of file in phar:///var/www/sites/test/wp-cli.phar/vendor/wp-cli/eval-command/src/Eval_Command.php(37) : eval()'d code on line 1
Parse error: syntax error, unexpected end of file in phar:///var/www/sites/test/wp-cli.phar/vendor/wp-cli/eval-command/src/Eval_Command.php(37) : eval()'d code on line 1
```

This happens no matter what I put into the script, so I figure the problem isn't my script? The smallest test case I have is:

```
<?php
global $wpdb;
var_dump($wpdb);
```

which I call through:

```
php wp-cli.phar eval test.php
```

`--info` gives me:

```
PHP binary:	/usr/bin/php7.1
PHP version:	7.1.11-1+ubuntu17.04.1+deb.sury.org+1
php.ini used:	/etc/php/7.1/cli/php.ini
WP-CLI root dir:	phar://wp-cli.phar
WP-CLI vendor dir:	phar://wp-cli.phar/vendor
WP_CLI phar path:	/var/www/sites/test
WP-CLI packages dir:	
WP-CLI global config:	
WP-CLI project config:	
WP-CLI version:	1.4.1
```

I'll happily try to write a test/fix if someone points me into the right direction but at the moment I'm a bit lost.

**Comment by gitlost** [comment]
@lostfocus for a file the wp-cli command is `eval-file` !

The `eval` equivalent is `eval 'global $wpdb; var_dump($wpdb);'`

**Comment by lostfocus** [comment]
Thanks! Typical "problem is between chair and keyboard" error.
