### ISSUE TITLE
Error: 'example.php' does not exist.

### ISSUE THREAD

**Issue by shillshocked** [wp-cli/eval-command#43]
echo '<?php echo is_wp_error("foo") ? 1 : 0;' > example.php
wp eval-file example.php
Error: 'example.php' does not exist.

**Comment by schlessera** [comment]
I cannot replicate the above problem, it is likely a problem with your environment, not with WP-CLI itself.

GitHub issues are meant for enhancement requests and specific, reproducible bugs, not for general support questions. For support options, please review http://wp-cli.org/#support

The easiest way to get support is to join us in the #cli channel on the [Make WordPress Slack Team](https://make.wordpress.org/chat/).

**Comment by shillshocked** [comment]
Yes, it turned out I had to be su'd in as a particular user (the one which owned wordpress) and not root. Not sure why root couldn't find the files, it was the same location.

**Comment by shillshocked** [comment]
On further examination, with root you should use  --allow-root
