### ISSUE TITLE
`wp eval-file` and the `--use-include` parameter

### ISSUE THREAD

**Issue by maximejobin** [wp-cli/eval-command#70]
The README file says this package is included in WP-CLI.

That is true but I haven't been able to use the `--use-include` parameter of `eval-file` without explicitely installing the package manually. I just tried on a fresh install of WP CLI 2.7.1.

Am I missing something? Do I really have to install it manually each time?

**Comment by danielbachhuber** [comment]
@maximejobin The `--use-include` flag was included in [WP-CLI v2.8.0](https://make.wordpress.org/cli/2023/05/31/wp-cli-v2-8-0-release-notes/).
