### ISSUE TITLE
cli eval-file not read hooks...

### ISSUE THREAD

**Issue by leah-committed** [wp-cli/eval-command#72]
Hi,
i did it :docker-compose run --rm cli eval-file /var/www/html/wp-content/themes/twentytwentyone-child/acf_fields.php
to import ACF filed into my site.
it on hook:add_action( 'init',
but it not work

Maybe I need to activate HOOK in a different way?

**Comment by danielbachhuber** [comment]
Hey @leah-committed,

Sorry to hear you're having trouble. It's difficult to understand what the problem might be without reproducible steps, though.

Feel free to stop by the `#cli` channel on [WordPress.org Slack](https://make.wordpress.org/chat/) if you'd like help debugging further.
